plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
	maven {
		name = "ModMaven"
		url = "https://modmaven.dev"
	}
	maven {
		name = "CurseMaven"
		url = "https://cursemaven.com"
	}
}

loom {
	splitEnvironmentSourceSets()
	mods {
		"colorist" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	// Compatibility
	modCompileOnly "mezz.jei:jei-1.21.11-fabric-api:27.21.0.54"
	modRuntimeOnly "mezz.jei:jei-1.21.11-fabric:27.21.0.54"
}

processResources {
	def version = project.version
	inputs.property "version", version
	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
	options.encoding = 'UTF-8'
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName
	from("LICENSE") {
		rename { "${it}_$projectName" }
	}
}
